#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-dask
Version  : 2021.12.0
Release  : 141
URL      : https://files.pythonhosted.org/packages/18/23/8dea146e14e884e7e0a72738c6bc4ed2ab6939fffbd3ffa32330459861ef/dask-2021.12.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/18/23/8dea146e14e884e7e0a72738c6bc4ed2ab6939fffbd3ffa32330459861ef/dask-2021.12.0.tar.gz
Summary  : Parallel PyData with Task Scheduling
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-dask-license = %{version}-%{release}
Requires: pypi-dask-python = %{version}-%{release}
Requires: pypi-dask-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: dask
Provides: dask-python
Provides: dask-python3
BuildRequires : pypi(cloudpickle)
BuildRequires : pypi(fsspec)
BuildRequires : pypi(packaging)
BuildRequires : pypi(partd)
BuildRequires : pypi(pytest_runner)
BuildRequires : pypi(pyyaml)
BuildRequires : pypi(toolz)

%description
====
        
        |Build Status| |Coverage| |Doc Status| |Discourse| |Version Status| |NumFOCUS|
        
        Dask is a flexible parallel computing library for analytics.  See
        documentation_ for more information.
        
        
        LICENSE
        -------

%package license
Summary: license components for the pypi-dask package.
Group: Default

%description license
license components for the pypi-dask package.


%package python
Summary: python components for the pypi-dask package.
Group: Default
Requires: pypi-dask-python3 = %{version}-%{release}

%description python
python components for the pypi-dask package.


%package python3
Summary: python3 components for the pypi-dask package.
Group: Default
Requires: python3-core
Provides: pypi(dask)
Requires: pypi(cloudpickle)
Requires: pypi(fsspec)
Requires: pypi(packaging)
Requires: pypi(partd)
Requires: pypi(pyyaml)
Requires: pypi(toolz)

%description python3
python3 components for the pypi-dask package.


%prep
%setup -q -n dask-2021.12.0
cd %{_builddir}/dask-2021.12.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641431021
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-dask
cp %{_builddir}/dask-2021.12.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-dask/11121adb6817476c9a2f348de0b254ca5df12057
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-dask/11121adb6817476c9a2f348de0b254ca5df12057

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
